import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import styles from '../../styles/AnimeDetail.module.css'; // We'll create this CSS file

interface AnimeDetails {
  id: string;
    title: string;
      image: string;
        description: string;
          genres: string[];
            episodes: {
                id: string;
                    number: number;
                        title?: string;
                            url?: string;
                              }[];
                                // Add other properties you might need like releaseDate, status, etc.
                                }

                                export default function AnimeDetail() {
                                  const router = useRouter();
                                    const { id } = router.query; // The anime ID from the URL
                                      const [animeDetails, setAnimeDetails] = useState<AnimeDetails | null>(null);
                                        const [loading, setLoading] = useState<boolean>(true);
                                          const [error, setError] = useState<string | null>(null);

                                            const consumetApiUrl = process.env.NEXT_PUBLIC_CONSUMET_API_URL;

                                              useEffect(() => {
                                                  const fetchAnimeDetails = async () => {
                                                        if (!id) return; // Don't fetch if ID is not available yet

                                                              setLoading(true);
                                                                    setError(null);

                                                                          if (!consumetApiUrl) {
                                                                                  setError('Consumet API URL is not configured. Please check your .env.local file.');
                                                                                          setLoading(false);
                                                                                                  return;
                                                                                                        }

                                                                                                              try {
                                                                                                                      // Use the gogoanime provider to fetch details
                                                                                                                              const response = await axios.get<AnimeDetails>(`${consumetApiUrl}/anime/gogoanime/info/${id}`);
                                                                                                                                      setAnimeDetails(response.data);
                                                                                                                                            } catch (err) {
                                                                                                                                                    console.error('Error fetching anime details:', err);
                                                                                                                                                            setError('Failed to load anime details. Please try again.');
                                                                                                                                                                  } finally {
                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                }
                                                                                                                                                                                    };

                                                                                                                                                                                        fetchAnimeDetails();
                                                                                                                                                                                          }, [id, consumetApiUrl]); // Re-run effect if ID or API URL changes

                                                                                                                                                                                            if (loading) {
                                                                                                                                                                                                return <div className={styles.loading}>Loading anime details...</div>;
                                                                                                                                                                                                  }

                                                                                                                                                                                                    if (error) {
                                                                                                                                                                                                        return <div className={styles.error}>{error}</div>;
                                                                                                                                                                                                          }

                                                                                                                                                                                                            if (!animeDetails) {
                                                                                                                                                                                                                return <div className={styles.noData}>No anime details found.</div>;
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                        <div className={styles.container}>
                                                                                                                                                                                                                              <Head>
                                                                                                                                                                                                                                      <title>{animeDetails.title} - Imtiaz's Anime Stream</title>
                                                                                                                                                                                                                                            </Head>

                                                                                                                                                                                                                                                  <main className={styles.main}>
                                                                                                                                                                                                                                                          <Link href="/" className={styles.backButton}>&larr; Back to Search</Link>

                                                                                                                                                                                                                                                                  <div className={styles.animeHeader}>
                                                                                                                                                                                                                                                                            <img src={animeDetails.image} alt={animeDetails.title} className={styles.animeImage} />
                                                                                                                                                                                                                                                                                      <div className={styles.animeInfo}>
                                                                                                                                                                                                                                                                                                  <h1 className={styles.animeTitle}>{animeDetails.title}</h1>
                                                                                                                                                                                                                                                                                                              <p className={styles.animeDescription}>{animeDetails.description}</p>
                                                                                                                                                                                                                                                                                                                          <p className={styles.animeGenres}>Genres: {animeDetails.genres.join(', ')}</p>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                    <h2 className={styles.episodesTitle}>Episodes:</h2>
                                                                                                                                                                                                                                                                                                                                                            <ul className={styles.episodeList}>
                                                                                                                                                                                                                                                                                                                                                                      {animeDetails.episodes.length > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                  animeDetails.episodes.map((episode) => (
                                                                                                                                                                                                                                                                                                                                                                                                <li key={episode.id} className={styles.episodeItem}>
                                                                                                                                                                                                                                                                                                                                                                                                                <Link href={`/watch/${episode.id}`} className={styles.episodeLink}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  Episode {episode.number}: {episode.title || 'No Title'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>No episodes found for this anime.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <footer className={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  href="https://github.com/consumet/api.consumet.org"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Powered by Consumet API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            