import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import styles from '../../styles/Watch.module.css'; // We'll create this CSS file

interface EpisodeStreamingLink {
  url: string;
    quality: string;
      isM3U8: boolean; // Indicates if it's an HLS stream
      }

      export default function WatchPage() {
        const router = useRouter();
          const { episodeId } = router.query;
            const [streamingLinks, setStreamingLinks] = useState<EpisodeStreamingLink[]>([]);
              const [selectedQualityUrl, setSelectedQualityUrl] = useState<string | null>(null);
                const [loading, setLoading] = useState<boolean>(true);
                  const [error, setError] = useState<string | null>(null);

                    const consumetApiUrl = process.env.NEXT_PUBLIC_CONSUMET_API_URL;

                      useEffect(() => {
                          const fetchStreamingLinks = async () => {
                                if (!episodeId) return;

                                      setLoading(true);
                                            setError(null);
                                                  setStreamingLinks([]);
                                                        setSelectedQualityUrl(null);

                                                              if (!consumetApiUrl) {
                                                                      setError('Consumet API URL is not configured. Please check your .env.local file.');
                                                                              setLoading(false);
                                                                                      return;
                                                                                            }

                                                                                                  try {
                                                                                                          // Use the gogoanime provider to watch
                                                                                                                  const response = await axios.get<{ sources: EpisodeStreamingLink[] }>(
                                                                                                                            `${consumetApiUrl}/anime/gogoanime/watch/${episodeId}`
                                                                                                                                    );

                                                                                                                                            const links = response.data.sources;
                                                                                                                                                    if (links && links.length > 0) {
                                                                                                                                                              setStreamingLinks(links);
                                                                                                                                                                        // Auto-select the best quality available, preferring non-m3u8 if possible, or highest quality
                                                                                                                                                                                  const bestQuality = links.find(link => link.quality === 'auto') || links.find(link => !link.isM3U8) || links[links.length - 1];
                                                                                                                                                                                            setSelectedQualityUrl(bestQuality.url);
                                                                                                                                                                                                    } else {
                                                                                                                                                                                                              setError('No streaming links found for this episode.');
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                    console.error('Error fetching streaming links:', err);
                                                                                                                                                                                                                                            setError('Failed to load streaming links. This episode might not be available or the API has an issue.');
                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                        fetchStreamingLinks();
                                                                                                                                                                                                                                                                          }, [episodeId, consumetApiUrl]);

                                                                                                                                                                                                                                                                            const handleQualityChange = (url: string) => {
                                                                                                                                                                                                                                                                                setSelectedQualityUrl(url);
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                        <div className={styles.container}>
                                                                                                                                                                                                                                                                                              <Head>
                                                                                                                                                                                                                                                                                                      <title>Watch Episode {episodeId} - Imtiaz's Anime Stream</title>
                                                                                                                                                                                                                                                                                                            </Head>

                                                                                                                                                                                                                                                                                                                  <main className={styles.main}>
                                                                                                                                                                                                                                                                                                                          <Link href={`/anime/${router.query.fromAnimeId || ''}`} className={styles.backButton}>&larr; Back to Anime Details</Link> {/* Adjust if you pass parent anime ID */}

                                                                                                                                                                                                                                                                                                                                  <h1 className={styles.title}>Watching Episode {episodeId}</h1> {/* You might want to pass episode title here */}

                                                                                                                                                                                                                                                                                                                                          {loading && <div className={styles.loading}>Loading video...</div>}
                                                                                                                                                                                                                                                                                                                                                  {error && <div className={styles.error}>{error}</div>}

                                                                                                                                                                                                                                                                                                                                                          {selectedQualityUrl && !loading && (
                                                                                                                                                                                                                                                                                                                                                                    <div className={styles.videoWrapper}>
                                                                                                                                                                                                                                                                                                                                                                                <video
                                                                                                                                                                                                                                                                                                                                                                                              controls
                                                                                                                                                                                                                                                                                                                                                                                                            autoPlay
                                                                                                                                                                                                                                                                                                                                                                                                                          width="100%"
                                                                                                                                                                                                                                                                                                                                                                                                                                        height="auto"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={selectedQualityUrl} // Key prop forces video re-render on source change
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={styles.videoPlayer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <source src={selectedQualityUrl} type={selectedQualityUrl.includes('.m3u8') ? 'application/x-mpegURL' : 'video/mp4'} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Your browser does not support the video tag.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {streamingLinks.length > 1 && !loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className={styles.qualitySelector}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>Select Quality:</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {streamingLinks.map((link) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={link.quality}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => handleQualityChange(link.url)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className={`${styles.qualityButton} ${selectedQualityUrl === link.url ? styles.active : ''}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {link.quality} {link.isM3U8 && '(HLS)'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <footer className={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="https://github.com/consumet/api.consumet.org"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Powered by Consumet API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    