import { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';
import styles from '../styles/Home.module.css'; // We'll create this CSS file

interface AnimeResult {
  id: string;
    title: string;
      image: string;
        releaseDate?: string;
          url?: string;
          }

          export default function Home() {
            const [searchTerm, setSearchTerm] = useState<string>('');
              const [searchResults, setSearchResults] = useState<AnimeResult[]>([]);
                const [loading, setLoading] = useState<boolean>(false);
                  const [error, setError] = useState<string | null>(null);

                    const consumetApiUrl = process.env.NEXT_PUBLIC_CONSUMET_API_URL;

                      const handleSearch = async (e: React.FormEvent) => {
                          e.preventDefault();
                              if (!searchTerm.trim()) return;

                                  setLoading(true);
                                      setError(null);
                                          setSearchResults([]); // Clear previous results

                                              if (!consumetApiUrl) {
                                                    setError('Consumet API URL is not configured. Please check your .env.local file.');
                                                          setLoading(false);
                                                                return;
                                                                    }

                                                                        try {
                                                                              // Use the gogoanime provider for search (you can change this if you use another)
                                                                                    const response = await axios.get<AnimeResult[]>(`${consumetApiUrl}/anime/gogoanime/${searchTerm}`);
                                                                                          setSearchResults(response.data);
                                                                                              } catch (err) {
                                                                                                    console.error('Error searching anime:', err);
                                                                                                          setError('Failed to search anime. Please try again or check your API URL.');
                                                                                                              } finally {
                                                                                                                    setLoading(false);
                                                                                                                        }
                                                                                                                          };

                                                                                                                            return (
                                                                                                                                <div className={styles.container}>
                                                                                                                                      <Head>
                                                                                                                                              <title>Anime Stream - Imtiaz's Project</title>
                                                                                                                                                      <meta name="description" content="Stream anime using Consumet API" />
                                                                                                                                                              <link rel="icon" href="/favicon.ico" />
                                                                                                                                                                    </Head>

                                                                                                                                                                          <main className={styles.main}>
                                                                                                                                                                                  <h1 className={styles.title}>
                                                                                                                                                                                            Welcome to Imtiaz&apos;s Anime Stream!
                                                                                                                                                                                                    </h1>

                                                                                                                                                                                                            <form onSubmit={handleSearch} className={styles.searchForm}>
                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                              placeholder="Search for an anime..."
                                                                                                                                                                                                                                                          value={searchTerm}
                                                                                                                                                                                                                                                                      onChange={(e) => setSearchTerm(e.target.value)}
                                                                                                                                                                                                                                                                                  className={styles.searchInput}
                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                      <button type="submit" className={styles.searchButton} disabled={loading}>
                                                                                                                                                                                                                                                                                                                  {loading ? 'Searching...' : 'Search'}
                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                            {error && <p className={styles.error}>{error}</p>}

                                                                                                                                                                                                                                                                                                                                                    <div className={styles.resultsGrid}>
                                                                                                                                                                                                                                                                                                                                                              {searchResults.length === 0 && !loading && !error && searchTerm.trim() !== '' && (
                                                                                                                                                                                                                                                                                                                                                                          <p>No anime found for &quot;{searchTerm}&quot;.</p>
                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                              {searchResults.map((anime) => (
                                                                                                                                                                                                                                                                                                                                                                                                          <Link key={anime.id} href={`/anime/${anime.id}`} className={styles.card}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <img src={anime.image} alt={anime.title} className={styles.cardImage} />
                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3 className={styles.cardTitle}>{anime.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {anime.releaseDate && <p className={styles.cardInfo}>Released: {anime.releaseDate}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer className={styles.footer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="https://github.com/consumet/api.consumet.org"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Powered by Consumet API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                